version: '2'
services:
  db:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TEST
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
  app:
    build: ./php/
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    stdin_open: true
    tty: true
