version: '2'
services:
  db:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_schema
    ports:
      - "3306:3306"
  app:
    build: ./php/
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./src:/var/www/html
    stdin_open: true
    tty: true
